<?php

return [
    'PAYMENT_GATEWAY_URL' => env('PAYMENT_GATEWAY_URL', ''),
    'PAYMENT_GATEWAY_EMAIL' => env('PAYMENT_GATEWAY_EMAIL', ''),
    'PAYMENT_GATEWAY_PASSWORD' => env('PAYMENT_GATEWAY_PASSWORD', ''),
    'PAYMENT_GATEWAY_API_KEY' => env('PAYMENT_GATEWAY_API_KEY', ''),
    'PAYMENT_GATEWAY_WEBHOOK_URL' => env('PAYMENT_GATEWAY_WEBHOOK_URL', '')
];